universe              = vanilla
request_memory        = 4GB
PeriodicHold          = (NumJobStarts>=1 && JobStatus == 1)
Notification          = Never
executable            = /bin/bash
arguments             = "oneforall.sh $(cfg)"
log                   = logs/$(cfg).all.log
output                = logs/$(cfg).all.out
error                 = logs/$(cfg).all.err
queue cfg in (
    config_bdt_nom.yaml
)
