universe              = vanilla
PeriodicHold          = (NumJobStarts>=1 && JobStatus == 1)
request_memory        = 6GB
Notification          = Never
executable            = /bin/bash
arguments             = "oneforall_tree.sh $(cfg)"
log                   = logs/$(cfg).log
output                = logs/$(cfg).out
error                 = logs/$(cfg).err

queue cfg matching (config_bdt_flat_*.yaml)
