#config.yaml
input:
  photon_jet_file_root_dir: "/sphenix/user/shuhangli/ppg12/anatreemaker/macro_maketree/sim/run21/"
  photon_jet_file_branch_dir: "/condorout_waveform/caloana0220.root"
  data_file: "/sphenix/tg/tg01/commissioning/CaloCalibWG/sli/ppg12/ana462/ana462_newlist/combine0213.root"
  tree: "slimtree"
  cluster_node_name: "CLUSTERINFO_CEMC_NO_SPLIT"
  unfold_input: "results/MC_efficiency_photon5.root"

output:
  eff_outfile: "/sphenix/user/shuhangli/ppg12/efficiencytool/results/MC_efficiency"
  response_outfile: "/sphenix/user/shuhangli/ppg12/efficiencytool/results/MC_response"
  data_outfile: "/sphenix/user/shuhangli/ppg12/efficiencytool/results/data_histo"
  var_type: "nom"
  final_outfile: "/sphenix/user/shuhangli/ppg12/efficiencytool/results/Photon_final"

analysis:
  isbackground: 0
  eta_bins: [-0.7, 0.7]
  vertex_cut: 30.0
  truth_iso_max: 4.0
  reco_iso_min: -20.0
  #reco_iso_max_b: 0.803709
  #reco_iso_max_s: 0.0284341
  reco_iso_max_b: 0.653777
  reco_iso_max_s: 0.0324863
  #reco_iso_max_b: 3.0
  #reco_iso_max_s: 0.0
  reco_noniso_min_shift: 2.0
  reco_noniso_max: 20.0
  reco_min_ET: 5.0
  cone_size: 3
  eff_dR: 0.1
  trigger_used: 26
  pT_bins: [8,10, 12, 14, 16, 20, 30, 35]
  pT_bins_truth:  [7,8,10, 12, 14, 16, 20, 30, 35]

  tight:
    reta77_min: 0.0
    reta77_max: 1.0

    rhad33_max: 1.0
    rhad33_min: 0.00

    w72_max: 1.0
    w72_min: 0.0

    re11_E_max: 1.0
    re11_E_min: 0.0

    CNN_max: 1.0
    CNN_min: 0.0
    #CNN_min: 0.8

    #correlation
    et1_max: 1.0
    et1_min: 0.9
    #correlation
    e32_over_e35_max: 1.0
    e32_over_e35_min: 0.92

    #correlation
    weta_cogx_max: 0.15
    weta_cogx_min: 0.0
    #correlation
    prob_max: 1.0
    prob_min: 0.0

    #small correlation
    e11_over_e33_max: 1.0
    e11_over_e33_min: 0.5

    #small correlation
    et4_max: 0.2
    et4_min: 0.0

    #w32 small correlation
    w32_max: 0.4
    w32_min: 0.0


  non_tight:
    reta77_min: 0.0
    reta77_max: 1.0

    rhad33_max: 0.1
    rhad33_min: 0.00

    w72_max: 1.0
    w72_min: 0.0

    re11_E_max: 1.0
    re11_E_min: 0.0

    CNN_max: 1.0
    CNN_min: 0.0
    #correlation
    et1_max: 1.0
    et1_min: 0.9
    #correlation
    e32_over_e35_max: 1.0
    e32_over_e35_min: 0.92

    #correlation
    weta_cogx_max: 0.8
    weta_cogx_min: 0.3
    #correlation
    prob_max: 1.0
    prob_min: 0.0

    #small correlation
    e11_over_e33_max: 1.0
    e11_over_e33_min: 0.0
  
    #small correlation
    et4_max: 1.0
    et4_min: 0.0

    #w32 small correlation
    w32_max: 1.0
    w32_min: 0.0

  common:
    wr_cogx_bound: 0.4
    cluster_weta_cogx_bound: 0.8

    prob_max: 1.0
    prob_min: 0.0

    e11_over_e33_max: 0.98
    e11_over_e33_min: 0.0






  unfold:
    resultit: 2
    resultleak: 1
    reweight: 1




